project:
  type: book
  output-dir: docs
book:
  title: "CASA0025: \n Building Spatial Applications with Big Data"
  author: "[Dr. Ollie Ballinger](https://oballinger.github.io)"
  date: "01/10/2024"
  chapters:
    - index.qmd
    - part: "A. SQL"
      chapters:
        - W1_intro.qmd
        - W2_SQL.qmd
        - W3_postgis1.qmd
        - W4_postgis2.qmd
        - W5_quiz.qmd
    - part: "B. Google Earth Engine"
      chapters:
        - W6_RS.qmd
        - W7_RS_data.qmd
        - W8_refineries.qmd
        - W9_blast.qmd
        - W10_ships.qmd
        - object_detection.qmd
    - part: "GEE Textbook"
      chapters:
        - F1.qmd
        - F2.qmd
        - F4.qmd
        - F5.qmd
  repo-url: https://github.com/oballinger/CASA0025/
  google-analytics: G-RK9ZLZQ6GL
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  favicon: favicon.ico
  sidebar:
    logo: logo_white.png
    collapse-level: 1


bibliography: references.bib

format:
  html:
    theme:
      dark: darkly
      light: cosmo
    code-copy: true
    code-overflow: wrap
    highlight-style: monokai.theme
    linkcolor: "#34a832"        

  pdf:
    documentclass: scrreprt
    header-includes:
      - \makeatletter
      - \@addtoreset{chapter}{part}
      - \makeatother         
  epub:
    cover-image: cover.png
